# -*- coding: utf-8 -*-
"""optimization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IYFM2BtJaOsxTa3-x2ACP_5XaP7DigYO
"""

"""
optimization.py
C3 — Optimization Module
Author: Kenia Gabriela Hermida Núñez
Module: optimize_parameters(model, X, y) → optimal_params, convergence_history
Purpose: Take the regression model produced by C2 (regression.py) and optimize its coefficients to further
minimize RMSE, using:
      1. Gradient descent (custom, step-by-step)
      2. scipy BFGS (for comparison)
Then plot the convergence curve and run a sensitivity analysis on one constraint.
Depends on:
    regression.py (C2) — fit_regression() is called first to get the initial
                          model; optimizer.py then refines those coefficients.
Complexity: O(k · n)  where k = number of iterations, n = number of samples
"""

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from scipy.optimize import minimize

# Import the existing regression model from C2
from regression import fit_regression

# Internal helpers
def _build_design_matrix(X: np.ndarray, degree: int) -> np.ndarray:
    """
    Reconstruct the polynomial design matrix consistent with regression.py.
    [1, x, x^2, x^3] up to degree.
    """
    if X.ndim == 1:
        X = X.reshape(-1, 1)

    X_poly = X.copy()
    if degree >= 2:
        X_poly = np.hstack([X_poly, X ** 2])
    if degree >= 3:
        X_poly = np.hstack([X_poly, X ** 3])

    return np.hstack([np.ones((X_poly.shape[0], 1)), X_poly])


def _rmse(coeffs: np.ndarray, X_design: np.ndarray, y: np.ndarray) -> float:
    """Objective function f(theta) = RMSE(y, y_hat)"""
    y_hat = X_design @ coeffs
    return float(np.sqrt(np.mean((y - y_hat) ** 2)))


def _rmse_gradient(
    coeffs: np.ndarray, X_design: np.ndarray, y: np.ndarray
) -> np.ndarray:
    """Analytical gradient of RMSE w.r.t. theta:
        d(RMSE)/d(theta) = -(1 / (n * RMSE)) * X^T (y - X*theta)"""
    n = len(y)
    y_hat = X_design @ coeffs
    residuals = y - y_hat
    rmse_val = float(np.sqrt(np.mean(residuals ** 2)))

    if rmse_val < 1e-12:
        return np.zeros_like(coeffs)

    return -(1.0 / (n * rmse_val)) * (X_design.T @ residuals)

# Public API
def optimize_parameters(
    model_coeffs: np.ndarray,
    X: np.ndarray,
    y: np.ndarray,
    degree: int = 1,
    learning_rate: float = 1e-4,
    max_iterations: int = 1000,
    tolerance: float = 1e-6,
) -> tuple[np.ndarray, list[float]]:
    """
    Optimize the coefficients of an EXISTING regression model (from C2)
    to further minimize RMSE.
    The function receives the coefficients already produced by fit_regression()
    (C2) as the warm starting point theta_0 — it does NOT refit from scratch.
    It then applies gradient descent and compares with scipy BFGS.

    Parameters:

    model_coeffs : np.ndarray
        Coefficient vector returned by regression.fit_regression() — used
        as the starting point theta_0 for optimization.
    X : np.ndarray
        Feature matrix (n samples x m features).
    y : np.ndarray
        Target vector — vehicle counts / hour (length n).
    degree : int
        Polynomial degree used when the model was originally fit (1, 2, or 3).
    learning_rate : float
        Step size for gradient descent (default 1e-4).
    max_iterations : int
        Maximum gradient-descent iterations (default 1000).
    tolerance : float
        Convergence threshold on RMSE improvement (default 1e-6).

    Returns:

    optimal_params : np.ndarray
        Refined coefficient vector that achieves a lower (or equal) RMSE
        than the original model from C2.
    convergence_history : list[float]
        RMSE recorded at every gradient-descent iteration.

    Raises:

    AssertionError
        If len(X) <= 10  (pseudocode assertion: assert len(X) > 10).
    ValueError
        If X and y lengths are incompatible.
    """

    # Assertion  (C3 pseudocode: assert len(X) > 10)
    assert len(X) > 10, (
        f"[C3] AssertionError: dataset must have more than 10 samples "
        f"(got {len(X)})."
    )

    if len(X) != len(y):
        raise ValueError(
            f"[C3] X and y must have the same length "
            f"(X={len(X)}, y={len(y)})."
        )

    if X.ndim == 1:
        X = X.reshape(-1, 1)

    # Step 1 — Define objective function f(theta) = RMSE
    X_design = _build_design_matrix(X, degree)

    # Step 2 — Initialize theta_0 from the EXISTING C2 model coefficients
    theta_init = model_coeffs.copy()
    rmse_before = _rmse(theta_init, X_design, y)
    print(f"[C3] Starting RMSE from C2 model : {rmse_before:.4f}")

    # Step 3a — Apply gradient descent optimization
    convergence_history: list[float] = []
    theta_gd = theta_init.copy()

    for _ in range(max_iterations):
        current_rmse = _rmse(theta_gd, X_design, y)
        convergence_history.append(current_rmse)   # Step 4 — track per iteration

        grad = _rmse_gradient(theta_gd, X_design, y)
        theta_gd = theta_gd - learning_rate * grad

        # Check convergence
        if len(convergence_history) > 1:
            improvement = abs(convergence_history[-2] - convergence_history[-1])
            if improvement < tolerance:
                break

    rmse_gd = _rmse(theta_gd, X_design, y)

    # Step 3b — Compare with scipy BFGS / minimize
    result_bfgs = minimize(
        fun=_rmse,
        x0=theta_init,
        args=(X_design, y),
        method="BFGS",
        jac=_rmse_gradient,
        options={"maxiter": max_iterations, "gtol": tolerance},
    )
    theta_bfgs = result_bfgs.x
    rmse_bfgs = _rmse(theta_bfgs, X_design, y)

    # Step 5 — Return parameters minimizing RMSE
    if rmse_bfgs < rmse_gd:
        optimal_params = theta_bfgs
        print(f"[C3] BFGS selected           → RMSE = {rmse_bfgs:.4f}")
    else:
        optimal_params = theta_gd
        print(f"[C3] Gradient descent selected → RMSE = {rmse_gd:.4f}")

    rmse_after = min(rmse_gd, rmse_bfgs)
    improvement_pct = (
        100 * (rmse_before - rmse_after) / rmse_before if rmse_before > 0 else 0
    )
    print(f"[C3] RMSE improvement over C2 model : {improvement_pct:.2f}%")
    print(f"[C3] Convergence steps              : {len(convergence_history)}")

    return optimal_params, convergence_history


# Step 4 — Plot convergence curve (objective value vs iteration)
def plot_convergence_curve(
    convergence_history: list[float],
    save_path: str | None = "reports/figures/convergence_curve.png",
    show: bool = True,
) -> None:
    """
    Plot the RMSE (objective value f(theta)) at every gradient-descent
    iteration.

    Parameters:
    convergence_history : list[float]
        Returned by optimize_parameters().
    save_path : str or None
        File path to save the figure. None = skip saving.
    show : bool
        Display interactively (default True).
    """
    if not convergence_history:
        print("[C3] convergence_history is empty — nothing to plot.")
        return

    iterations = list(range(1, len(convergence_history) + 1))

    fig, ax = plt.subplots(figsize=(9, 5))

    ax.plot(iterations, convergence_history, color="#0077B6", linewidth=2,
            label="RMSE per iteration")
    ax.axhline(convergence_history[-1], color="#E63946", linewidth=1.2,
               linestyle="--",
               label=f"Final RMSE = {convergence_history[-1]:.4f}")

    ax.set_xlabel("Iteration", fontsize=12)
    ax.set_ylabel("Objective value  f(theta) = RMSE", fontsize=12)
    ax.set_title(
        "C3 — Optimization Convergence Curve\n"
        "Gradient Descent: RMSE vs Iteration",
        fontsize=13, fontweight="bold"
    )
    ax.legend(fontsize=11)
    ax.grid(True, linestyle="--", alpha=0.5)
    fig.tight_layout()

    if save_path:
        out = Path(save_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(out, dpi=150)
        print(f"[C3] Convergence curve saved → {out}")

    if show:
        plt.show()

    plt.close(fig)


# Step 5 — Sensitivity analysis: vary one constraint
def sensitivity_analysis(
    model_coeffs: np.ndarray,
    X: np.ndarray,
    y: np.ndarray,
    degree: int = 1,
    param_index: int = 1,
    perturbation_range: np.ndarray | None = None,
) -> dict:
    """
    Vary one coefficient of the optimized model and observe how RMSE responds.

    Parameters:
    model_coeffs : np.ndarray
        The OPTIMIZED coefficients returned by optimize_parameters().
    X : np.ndarray
        Feature matrix.
    y : np.ndarray
        Target vector.
    degree : int
        Polynomial degree.
    param_index : int
        Index of the coefficient to perturb (0 = intercept, 1 = theta_1, ...).
    perturbation_range : np.ndarray, optional
        Multipliers applied to the chosen coefficient.
        Defaults to np.linspace(0.5, 1.5, 21) — plus/minus 50% in 5% steps.

    Returns:
    dict with keys:
        "param_values"  — actual values of the perturbed coefficient tested
        "rmse_values"   — corresponding RMSE at each value
        "optimal_value" — coefficient value that yields the lowest RMSE
    """
    assert len(X) > 10, "[C3] sensitivity_analysis requires more than 10 samples."

    if perturbation_range is None:
        perturbation_range = np.linspace(0.5, 1.5, 21)

    if X.ndim == 1:
        X = X.reshape(-1, 1)

    X_design = _build_design_matrix(X, degree)
    base_value = model_coeffs[param_index]

    param_values, rmse_values = [], []

    for multiplier in perturbation_range:
        theta_perturbed = model_coeffs.copy()
        perturbed_val = base_value * multiplier
        theta_perturbed[param_index] = perturbed_val
        param_values.append(perturbed_val)
        rmse_values.append(_rmse(theta_perturbed, X_design, y))

    best_idx = int(np.argmin(rmse_values))
    print(
        f"[C3] Sensitivity on theta[{param_index}]: "
        f"best value = {param_values[best_idx]:.4f} "
        f"-> RMSE = {rmse_values[best_idx]:.4f}"
    )

    return {
        "param_values": param_values,
        "rmse_values": rmse_values,
        "optimal_value": param_values[best_idx],
    }


# CLI — demo: runs C2 first, then passes its model to C3
if __name__ == "__main__":
    import csv

    CSV_PATH = Path("data/processed/df.csv")
    X_data, y_data = None, None


    # Try to load real data produced by data_loader.py (C1)
    if CSV_PATH.exists():
        print(f"[C3] Loading processed data from {CSV_PATH} ...")
        hourly: dict[int, int] = {}

        with open(CSV_PATH, newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                if row.get("day_type") == "weekday":
                    h = int(row["hour"])
                    hourly[h] = hourly.get(h, 0) + 1

        if len(hourly) > 10:
            hours = sorted(hourly.keys())
            X_data = np.array(hours, dtype=float)
            y_data = np.array([hourly[h] for h in hours], dtype=float)
            print(f"[C3] {len(X_data)} hourly buckets loaded.")
        else:
            print("[C3] Not enough data in CSV — falling back to synthetic.")

    # Fallback: synthetic traffic-like data
    if X_data is None:
        print("[C3] Using synthetic traffic data for demo.")
        rng = np.random.default_rng(42)
        X_data = np.arange(24, dtype=float)
        y_data = (
            50
            + 80 * np.exp(-0.5 * ((X_data - 8) / 2) ** 2)
            + 60 * np.exp(-0.5 * ((X_data - 17) / 2) ** 2)
            + rng.normal(0, 5, 24)
        )

    DEGREE = 2

    # Step A — Run C2 (regression.py) to get the initial model
    print("\n[C2] Fitting initial regression model ...")
    coeffs_c2, r2_c2, rmse_c2, y_hat_c2, _ = fit_regression(
        X_data, y_data, degree=DEGREE
    )
    print(f"[C2] Coefficients : {coeffs_c2}")
    print(f"[C2] R2           : {r2_c2:.4f}")
    print(f"[C2] RMSE         : {rmse_c2:.4f}")

    # Step B — Pass C2 model into C3 for optimization
    print("\n[C3] Optimizing C2 model parameters ...")
    optimal_coeffs, history = optimize_parameters(
        model_coeffs=coeffs_c2,    # <-- C2 model handed directly to C3
        X=X_data,
        y=y_data,
        degree=DEGREE,
    )

    # Step C — Plot convergence curve
    plot_convergence_curve(history)

    # Step D — Sensitivity analysis on the linear coefficient (theta_1)
    print("\n[C3] Running sensitivity analysis on theta[1] ...")
    sensitivity_analysis(
        model_coeffs=optimal_coeffs,
        X=X_data,
        y=y_data,
        degree=DEGREE,
        param_index=1,
    )